version: 2

models:
  - name: players_cleaned
    description: >
      Cleaned and structured player metadata from the bronze layer. 
      Includes standardised naming, typing, and selected useful fields.
    columns:
      - name: player_id
        description: Unique identifier for each NBA player.
        tests:
          - not_null
          - unique
      - name: full_name
        description: Full name of the player.
      - name: is_active
        description: Boolean flag indicating whether the player is active this season.
      - name: career_start_year
        description: First year the player appeared in the NBA.
      - name: career_end_year
        description: Most recent year the player appeared in the NBA.
      - name: team_name
        description: Name of the player's most recent team.
      - name: team_city
        description: City of the player's most recent team.
      - name: team_id
        description: ID of the team the player most recently played for.

  - name: player_stats_cleaned
    description: >
      Cleaned and typed per-game player stats from the bronze layer, filtered to include 
      only players who have played at least one game.
    columns:
      - name: player_id
        description: Foreign key to the player dimension table.
        tests:
          - not_null
      - name: player_name
        description: Name of the player (as given in raw stats).
      - name: team_abbreviation
        description: Team abbreviation the player played for.
      - name: points_per_game
        description: Average points scored per game.
      - name: assists_per_game
        description: Average assists per game.
      - name: rebounds_per_game
        description: Average rebounds per game.
      - name: field_goal_percentage
        description: Field goal shooting percentage.
      - name: plus_minus_score
        description: Net team point differential while player is on court.
      - name: games_played
        description: Total number of games played.
      - name: minutes_per_game
        description: Average minutes played per game.
      - name: season
        description: NBA season (e.g. 2023-24).